name: Deploy to Azure Storage

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Upload to Azure Storage
      uses: azure/azure-storage-blob@v1
      with:
        connection-string: ${{ secrets.AZURE_STORAGE_CONNECTION_STRING }}
        container-name: ${{ secrets.STORAGE_CONTAINER_NAME }}
        source: '.'  # The current directory where your HTML and CSS files are located
        destination: '/'
        clean: true

    - name: Purge Azure CDN endpoint
      uses: azure/azure-cli@v1
      with:
        inlineScript: |
          az cdn endpoint purge -g ${{ secrets.RESOURCE_GROUP }} -n ${{ secrets.CDN_ENDPOINT_NAME }} --profile-name <YourCDNProfileName> --content-paths '/*'
