name: Deploy to Azure Storage

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: List root directory contents
      run: ls -R .

    - name: List .github/workflows directory contents
      run: ls -R .github/workflows

    - name: Azure Login
      uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}

    - name: Upload to Azure Storage Blob
      run: |
        az storage blob upload-batch \
          --destination ${{ secrets.STORAGE_CONTAINER_NAME }} \
          --source CI-CD-Frontend \
          --account-name ${{ secrets.STORAGE_ACCOUNT_NAME }}
      env:
        AZURE_STORAGE_KEY: ${{ secrets.AZURE_STORAGE_KEY }}

    - name: Purge Azure CDN endpoint
      run: |
        az cdn endpoint purge \
          --resource-group ${{ secrets.RESOURCE_GROUP }} \
          --profile-name cloudresumefront \
          --name ${{ secrets.CDN_ENDPOINT_NAME }} \
          --content-paths '/*'
